---
- name: Deploy Containerized Application
  hosts: all
  become: yes # Run tasks with sudo privileges

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Python module
      ansible.builtin.pip:
        name: docker

    - name: Pull Docker image
      docker_image:
        name: agrawpri/2048-docker
        source: pull

    - name: Run container
      docker_container:
        name: 2048-app # e.g., my_web_app
        image: agrawpri/2048-docker:latest
        ports:
          - "80:80" # Map host port 80 to container port 80
        state: started
        restart_policy: always

